"""
Legacy 4-step job search flow.

This is a mechanical port of the original multi-agent pipeline (src/agents.py
+ src/tasks.py, both deleted) onto the plain src/llm.py wrapper - same
prompts, same behavior, same output-file layout. It's a transliteration,
not a redesign, and is the single entry point both main.py and
`jobsearch run` call into. Later phases (3-6) replace each step's logic
piece by piece until this module is deleted entirely.
"""

import re
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional

from src import config, llm
from src.tools import search_jobs
from src.prompts import (
    legacy_job_search,
    legacy_skills_analysis,
    legacy_interview_prep,
    legacy_career_advisory,
)

TASK_DISPLAY_NAMES = {
    "job_search": "Job Search",
    "skills_analysis": "Skills Analysis",
    "interview_prep": "Interview Prep",
    "career_advisory": "Career Advisory",
}


@dataclass
class LegacyRunResult:
    run_dir: Path
    report_path: Path
    step_outputs: Dict[str, str] = field(default_factory=dict)
    step_paths: Dict[str, Path] = field(default_factory=dict)


def _timestamp() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def _safe_role_slug(role: str) -> str:
    return re.sub(r"[^\w\-]+", "_", role.strip()).strip("_").lower()


def create_run_output_dir(role: str, timestamp: str, base_dir: Optional[Path] = None) -> Path:
    """
    Create a dedicated output folder for this run, named after the job
    role and timestamp, mirroring the original main.py behavior.

    Args:
        role: Job role being searched (used in the folder name)
        timestamp: Timestamp string shared by this run's files
        base_dir: Parent directory for run folders. Defaults to
            config.OUTPUT_DIR; tests pass tmp_path here instead.

    Returns:
        Path to the created run-specific output directory
    """
    base = base_dir if base_dir is not None else config.OUTPUT_DIR
    run_dir = base / f"{_safe_role_slug(role)}_{timestamp}"
    run_dir.mkdir(parents=True, exist_ok=True)
    return run_dir


def _save_step_output(output_dir: Path, step_name: str, raw_text: str, verbose: bool) -> Path:
    """
    Save one step's output to a Markdown file, reproducing the original
    create_task_callback's file format and progress messages.
    """
    display_name = TASK_DISPLAY_NAMES[step_name]
    timestamp = _timestamp()
    filepath = output_dir / f"{step_name}_{timestamp}.md"

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(f"# {display_name}\n\n")
        f.write(f"**Completed:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        f.write("---\n\n")
        f.write(raw_text)
        f.write("\n")

    print(f"✅ {display_name}")
    if verbose:
        print(f"   💾 Saved to: {filepath.name}")

    return filepath


def _save_final_report(output_dir: Path, role: str, location: str, step_outputs: Dict[str, str]) -> Path:
    """
    Save the final combined report, reproducing the original
    main.py.save_final_report's Markdown structure.

    Note: the "Full Report" body is step_outputs["career_advisory"]
    alone, not a concatenation of all four steps - this faithfully
    replicates CrewOutput.raw (confirmed by reading the installed
    package's source), which is only the last task's raw output. Don't
    "fix" this into a concatenation without a deliberate decision; a
    real redesign of the final report is Phase 3+ territory.
    """
    timestamp = _timestamp()
    filename = f"job_search_report_{timestamp}.md"
    filepath = output_dir / filename

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("# 🤖 Job Search AI Agent System - Final Report\n\n")

        f.write(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  \n")
        f.write(f"**Job Role:** {role}  \n")
        f.write(f"**Location:** {location}  \n\n")

        f.write("---\n\n")

        f.write("## Executive Summary\n\n")
        f.write(
            "This report was generated by an AI-agent pipeline built on **Claude**. "
            "Four steps collaborated to provide:\n\n"
            "1. 🔍 **Job Search Results** - Current openings matching your criteria\n"
            "2. 📚 **Skills Development Roadmap** - What to learn and how\n"
            "3. 🎤 **Interview Preparation** - Questions and strategies\n"
            "4. 💼 **Career Strategy** - Resume, LinkedIn, and application advice\n\n"
        )

        f.write("---\n\n")
        f.write("## Full Report\n\n")

        f.write(step_outputs["career_advisory"])

    return filepath


def run_legacy_flow(
    role: str,
    location: str,
    num_results: int,
    output_dir: Optional[Path] = None,
    verbose: bool = False,
) -> LegacyRunResult:
    """
    Run the legacy 4-step job search flow: Job Search, Skills Analysis,
    Interview Prep, Career Advisory.

    This is a plain library function with no try/except around
    KeyboardInterrupt/Exception - callers (main.py, src/cli.py) own that
    presentation-layer handling.

    Args:
        role: Job role to search for.
        location: Location to search in.
        num_results: Number of job listings to retrieve.
        output_dir: Directory to save this run's files in. Defaults to a
            new {role}_{timestamp}/ folder under config.OUTPUT_DIR.
        verbose: If True, step callbacks also print the saved file path.

    Returns:
        LegacyRunResult with paths and raw text for every step plus the
        combined report.
    """
    if output_dir is None:
        output_dir = create_run_output_dir(role, _timestamp())

    step_outputs: Dict[str, str] = {}
    step_paths: Dict[str, Path] = {}

    # Step 1: Job Search. search_jobs() is called directly (not via an
    # Anthropic tool-use loop) - the original task description already
    # spelled out the exact call params, so the model wasn't making a
    # real decision here.
    search_results = search_jobs(role, location, num_results)
    job_search_output = llm.complete(
        task="legacy_job_search",
        system=legacy_job_search.SYSTEM,
        user=legacy_job_search.build_user_prompt(role, location, num_results, search_results),
    )
    step_outputs["job_search"] = job_search_output
    step_paths["job_search"] = _save_step_output(output_dir, "job_search", job_search_output, verbose)

    # Steps 2-4 each take only the job search output as context, matching
    # the original: all three tasks had context=[job_search_task], none
    # chained off each other.
    for step_name, prompt_module in (
        ("skills_analysis", legacy_skills_analysis),
        ("interview_prep", legacy_interview_prep),
        ("career_advisory", legacy_career_advisory),
    ):
        output = llm.complete(
            task=f"legacy_{step_name}",
            system=prompt_module.SYSTEM,
            user=prompt_module.build_user_prompt(role, job_search_output),
        )
        step_outputs[step_name] = output
        step_paths[step_name] = _save_step_output(output_dir, step_name, output, verbose)

    report_path = _save_final_report(output_dir, role, location, step_outputs)

    return LegacyRunResult(
        run_dir=output_dir,
        report_path=report_path,
        step_outputs=step_outputs,
        step_paths=step_paths,
    )
